**Task - 1** *Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)*

In [ ]:
import pandas as pd
import numpy as np

data = np.random.rand(4, 4)  # Generate random values
df = pd.DataFrame(data)  # Create dataframe

In [ ]:
print("Random Values Using Numpy:\n", data, "\n","Converted DataFrame:\n", df)

Random Values Using Numpy:
 [[0.22383452 0.15730636 0.34832955 0.39496279]
 [0.96018814 0.26952126 0.01223278 0.62138452]
 [0.38686145 0.20257079 0.82728018 0.01577007]
 [0.81247585 0.64096119 0.10230234 0.354667  ]] 
 Converted DataFrame:
           0         1         2         3
0  0.223835  0.157306  0.348330  0.394963
1  0.960188  0.269521  0.012233  0.621385
2  0.386861  0.202571  0.827280  0.015770
3  0.812476  0.640961  0.102302  0.354667


**Task - 2** *Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'*

In [ ]:
df.columns = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']

In [ ]:
print("Renamed Column Names:\n", df.columns,"\n", "Updated Dataframe:\n", df)


Renamed Column Names:
 Index(['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4'], dtype='object') 
 Updated Dataframe:
    Random value 1  Random value 2  Random value 3  Random value 4
0        0.223835        0.157306        0.348330        0.394963
1        0.960188        0.269521        0.012233        0.621385
2        0.386861        0.202571        0.827280        0.015770
3        0.812476        0.640961        0.102302        0.354667


**Task - 3** *Find the descriptive statistics of the 'df' dataframe.*

In [ ]:
statistics = df.describe() # Descriptive statistics

In [ ]:
print("Descriptive Statistics:\n", statistics)

Descriptive Statistics:
        Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.595840        0.317590        0.322536        0.346696
std          0.347247        0.220454        0.365250        0.249906
min          0.223835        0.157306        0.012233        0.015770
25%          0.346105        0.191255        0.079785        0.269943
50%          0.599669        0.236046        0.225316        0.374815
75%          0.849404        0.362381        0.468067        0.451568
max          0.960188        0.640961        0.827280        0.621385


**Task - 4** *Check for the null values in 'df' and find the data type of the columns.*

In [ ]:
null_values = df.isnull() # Dataframe format showing True in place of null values
null_values_sum = df.isnull().sum() # Sum of all the null values in each column of the Dataframe
data_types = df.dtypes # Data type of each column

In [ ]:
print("Null Values:\n", null_values, "\n Sum Of Null Values In Each Column:\n", null_values_sum, "\n Data Types Of Columns:\n",data_types)

Null Values:
    Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False 
 Sum Of Null Values In Each Column:
 Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64 
 Data Types Of Columns:
 Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object


**Task - 5** *Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.*

In [ ]:
random_values_using_loc = df.loc[:, 'Random value 2':'Random value 3'] # Using location method
random_values_using_idx = df.iloc[:, 1:3] # Using index location method (excludes 3 in the df)

# Also can be written as
# random_values_using_loc = df.loc[:, ['Random value 2', 'Random value 3']] # Using location method
# random_values_using_idx = df.iloc[:, [1, 2]] # Using index location method


In [ ]:
print("'Random value 2' and 'Random value 3' using location method:\n", random_values_using_loc)

'Random value 2' and 'Random value 3' using location method:
    Random value 2  Random value 3
0        0.157306        0.348330
1        0.269521        0.012233
2        0.202571        0.827280
3        0.640961        0.102302


In [ ]:
print("'Random value 2' and 'Random value 3' using index location method:\n", random_values_using_idx)

'Random value 2' and 'Random value 3' using index location method:
    Random value 2  Random value 3
0        0.157306        0.348330
1        0.269521        0.012233
2        0.202571        0.827280
3        0.640961        0.102302
